language: java

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-mingw-w64-base
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - libc6-dev-i386

jdk:
  - openjdk7

install:
  - mvn install -DskipTests=true -DskipPkg=true
  
env:
  - TOOLCHAIN=$TRAVIS_BUILD_DIR/src/native/toolchains/Linux32.cmake SOURCE_DIR=$TRAVIS_BUILD_DIR/src/native/unix
  - TOOLCHAIN=$TRAVIS_BUILD_DIR/src/native/toolchains/Linux64.cmake SOURCE_DIR=$TRAVIS_BUILD_DIR/src/native/unix
  - TOOLCHAIN=$TRAVIS_BUILD_DIR/src/native/toolchains/Windows32.cmake SOURCE_DIR=$TRAVIS_BUILD_DIR/src/native/windows
  - TOOLCHAIN=$TRAVIS_BUILD_DIR/src/native/toolchains/Windows64.cmake SOURCE_DIR=$TRAVIS_BUILD_DIR/src/native/windows

script:
  - cd target && cmake $SOURCE_DIR -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN && make

after_script:
  - cd .. && mvn clean test
