language: java

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install mingw-w64 libc6-dev-i386 -y

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

install:
  - mvn install -DskipTests=true -DskipPkg=true

script:
  - mvn clean test
  - cd ./src/native/unix && cmake -DCMAKE_BUILD_TYPE=MINSIZEREL && make
