language: java

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-mingw-w64-base
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - libc6-dev-i386
      
env:
  - HALL_TRGT=x86
  - HALL_TRGT=x86_64

install:
  - "mvn install -DskipTests=true -DskipPkg=true -Phall.arch=:HALL_TRGT:"

script:
  - "mvn clean test -Phall.arch=:HALL_TRGT:"
