language: java

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-mingw-w64-base
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - libc6-dev-i386

install:
  - mvn install -DskipTests=true -DskipPkg=true

script:
  - mvn clean test
  - cd ./src/native/unix && cmake -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=../toolchains/Linux32.cmake && make
  - cd ./src/native/unix && cmake -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=../toolchains/Linux64.cmake && make
  - cd ./src/native/unix && cmake -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=../toolchains/Windows32.cmake && make
  - cd ./src/native/unix && cmake -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=../toolchains/Windows32.cmake && make
