language: java

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-mingw-w64-base
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - libc6-dev-i386

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y openjdk-8-jdk-headless:i386

install:
  - mvn install -DskipTests=true -DskipPkg=true
  
env:
  - TOOLCHAIN=$TRAVIS_BUILD_DIR/src/native/toolchains/Linux32.cmake BUILD_DIR=$TRAVIS_BUILD_DIR/target/natives/unix/x86_32 SOURCE_DIR=$TRAVIS_BUILD_DIR/src/native/unix
  - TOOLCHAIN=$TRAVIS_BUILD_DIR/src/native/toolchains/Linux64.cmake BUILD_DIR=$TRAVIS_BUILD_DIR/target/natives/unix/x86_64 SOURCE_DIR=$TRAVIS_BUILD_DIR/src/native/unix
  - TOOLCHAIN=$TRAVIS_BUILD_DIR/src/native/toolchains/Windows32.cmake BUILD_DIR=$TRAVIS_BUILD_DIR/target/natives/windows/x86_32 SOURCE_DIR=$TRAVIS_BUILD_DIR/src/native/windows
  - TOOLCHAIN=$TRAVIS_BUILD_DIR/src/native/toolchains/Windows64.cmake BUILD_DIR=$TRAVIS_BUILD_DIR/target/natives/windows/x86_64 SOURCE_DIR=$TRAVIS_BUILD_DIR/src/native/windows

before_script:
  - mvn clean test

script:
  - mkdir -p $BUILD_DIR && cd $BUILD_DIR && cmake "$SOURCE_DIR" -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN && make
