language: java

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - apt-fast
    packages:
      - cmake
      - cmake-data
      - mingw-w64
      - libc6-dev-i386

install:
  - mvn install -DskipTests=true -DskipPkg=true

script:
  - mvn clean test
  - cd ./src/native/unix && cmake -DCMAKE_BUILD_TYPE=MINSIZEREL && make
