language: java

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-mingw-w64-base
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - libc6-dev-i386

install:
  - mvn install -DskipTests=true -DskipPkg=true
  
env:
  - TOOLCHAIN_DIR=$TRAVIS_BUILD_DIR/src/native/toolchains
  - BUILD_DIR=$TRAVIS_BUILD_DIR/target/natives
  - SOURCE_DIR=$TRAVIS_BUILD_DIR/src/native

script:
  - mvn clean test
  - export WORK_DIR="$BUILD_DIR/linux/x86_32" && mkdir -p $WORK_DIR && cd $WORK_DIR && cmake "$SOURCE_DIR/unix" -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_DIR/Linux32.cmake && make
  - WORK_DIR="$BUILD_DIR/linux/x86_64" && mkdir -p $WORK_DIR && cd $WORK_DIR && cmake "$SOURCE_DIR/unix" -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_DIR/Linux64.cmake && make
  - WORK_DIR="$BUILD_DIR/windows/x86_32" && mkdir -p $WORK_DIR && cd $WORK_DIR && cmake "$SOURCE_DIR/windows" -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_DIR/Windows32.cmake && make
  - WORK_DIR="$BUILD_DIR/windows/x86_64" && mkdir -p $WORK_DIR && cd $WORK_DIR && cmake "$SOURCE_DIR/windows" -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_DIR/Windows64.cmake && make
