language: java

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - gcc-mingw-w64-i686
      - libc6-dev-i386

install:
  - mvn install -DskipTests=true -DskipPkg=true

script:
  - mvn clean test
  - cd ./src/native/unix && cmake -DCMAKE_BUILD_TYPE=MINSIZEREL && make
