language: java

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-5
      - gcc-mingw-w64-base
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - libc6-dev-i386
      
env:
  - TRGT_ARCH=x86
  - TRGT_ARCH=x86_64

install:
  - "mvn install -DskipTests=true -DskipPkg=true -Dsatellite.arch=$TRGT_ARCH"

script:
  - "mvn clean test -Dhatellite.arch=$TRGT_ARCH -pl :satellite-impl -am"
