language: java

install:
  - mvn install -DskipTests=true -DskipPkg=true

script:
  - mvn clean test cobertura:cobertura coveralls:report
  - cd ./src/native/unix && cmake -DCMAKE_BUILD_TYPE=MINSIZEREL && make
